import Head from 'next/head'

import Link from 'next/link'
import styles from '../styles/Home.module.css'


export default function Home() {

  return (
    <div className={styles.container}>
      <style jsx>
        {
          `
          h2{
            font-size: 38px;
          }
          h3{
            font-size: 28px;
          }
          `
        }
      </style>
      <Head>
        <title>Hunting coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="Code, code hunting, learn code, code blogs" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
      <main className={styles.main}>
        <h1 className={styles.title}>
     <a> Hunting Coder </a>
        </h1>
    <div className={styles.imageWrap}>
      <img className={styles.myImg} src="/coder.avif" width={207} height={138} alt="hunting code"/>
    </div>
        <p className={styles.description}>
          A blog for the hunting coders by the coder 
       
        </p>

      {/* <div className={`${styles1.con} ${styles2.con}`}> */}
      <div className="blogs">
        <h2>Popular Blogs</h2>
        <div className="blogitem">

          <h3>How to start javascript?</h3>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores, expedita!</p>
        </div>
        <div className="blogitem">
          <h3>How to start javascript?</h3>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores, expedita!</p>
        </div><div className="blogitem">
          <h3>How to start javascript?</h3>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores, expedita!</p>
        </div><div className="blogitem">
          <h3>How to start javascript?</h3>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores, expedita!</p>
        </div><div className="blogitem">
          <h3>How to start javascript?</h3>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores, expedita!</p>
        </div>
      </div>
      </main>

      <footer className={styles.footer}>
       
      </footer>
    </div>
  )
}
